name: 'GitHub Actions Fixer'
description: 'Validate and auto-fix common GitHub Actions workflow errors'
inputs:
  github-token:
    description: 'GitHub token (defaults to github.token)'
    required: false
    default: ''
  fail-on-error:
    description: 'Fail the action if errors are found (default: true)'
    required: false
    default: 'true'
  auto-fix:
    description: 'Automatically fix issues and create a commit (default: false)'
    required: false
    default: 'false'
  commit-message:
    description: 'Commit message for auto-fix (default: "fix: correct workflow validation issues")'
    required: false
    default: 'fix: correct workflow validation issues'
  claude-model:
    description: 'Claude model for AI-powered fixes (default: sonnet)'
    required: false
    default: 'sonnet'
  fix-prompt-template:
    description: 'Path to custom fix prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install yamllint
      shell: bash
      run: |
        pip install yamllint || true

    - name: Validate YAML files
      shell: bash
      id: validate
      run: |
        echo "Checking YAML files in .github/workflows/..."

        # Find all YAML files
        YAML_FILES=$(find .github -name "*.yml" -o -name "*.yaml" 2>/dev/null)

        if [ -z "$YAML_FILES" ]; then
          echo "No YAML files found in .github/"
          exit 0
        fi

        echo "$YAML_FILES" | while read -r file; do
          if [ ! -f "$file" ]; then
            continue
          fi

          echo "Validating: $file"

          # Check for common issues
          ISSUES=""

          # Issue 1: Validate YAML syntax
          if ! yamllint -d "{extends: default, rules: {line-length: {max: 200}, indentation: {spaces: 2}}}" "$file" 2>/dev/null; then
            # Try to parse with Python to get more details
            ERROR_OUTPUT=$(python3 -c "import yaml; yaml.safe_load(open('$file'))" 2>&1 || true)
            if [ -n "$ERROR_OUTPUT" ]; then
              ISSUES="${ISSUES}  - YAML syntax error: ${ERROR_OUTPUT}\n"
            fi
          fi

          # Issue 2: Check for common workflow mistakes
          # Missing runs-on
          if grep -q 'jobs:' "$file" && ! grep -q 'runs-on:' "$file"; then
            ISSUES="${ISSUES}  - Missing 'runs-on' in job\n"
          fi

          # Issue 3: Check for deprecated actions
          if grep -q 'actions/checkout@v1' "$file" || grep -q 'actions/checkout@v2' "$file"; then
            ISSUES="${ISSUES}  - Using deprecated checkout action version\n"
          fi

          # Issue 4: Check for missing permissions
          if grep -q 'jobs:' "$file" && ! grep -q 'permissions:' "$file"; then
            ISSUES="${ISSUES}  - Warning: Missing 'permissions' (recommended for security)\n"
          fi

          if [ -n "$ISSUES" ]; then
            echo "  Issues found:"
            echo -e "$ISSUES"

            # Track errors using a temporary file for subshell communication
            echo "1" >> /tmp/validation_errors.count

            # AI-powered fix if enabled
            if [ "${{ inputs.auto-fix }}" = "true" ]; then
              echo "  Attempting AI-powered fix for $file..."

              FIX_PROMPT_TEMPLATE="${{ inputs.fix-prompt-template }}"

              # Use custom template if provided, otherwise use built-in
              if [ -n "$FIX_PROMPT_TEMPLATE" ] && [ -f "$FIX_PROMPT_TEMPLATE" ]; then
                TEMPLATE_FILE="$FIX_PROMPT_TEMPLATE"
              else
                TEMPLATE_FILE="${{ github.action_path }}/templates/fix_prompt.txt"
              fi

              # Read template and replace placeholders safely using awk
              CURRENT_CONTENT=$(cat "$file")
              # Escape & and \\ for awk replacement safety
              FILE_ESCAPED=$(printf '%s\n' "$file" | sed 's/[&\\\\]/\\\\&/g')
              ISSUES_ESCAPED=$(printf '%s\n' "$ISSUES" | sed 's/[&\\\\]/\\\\&/g')
              CONTENT_ESCAPED=$(printf '%s\n' "$CURRENT_CONTENT" | sed 's/[&\\\\]/\\\\&/g')

              FIX_PROMPT=$(awk -v file="$FILE_ESCAPED" \
                                -v issues="$ISSUES_ESCAPED" \
                                -v content="$CONTENT_ESCAPED" \
                                '{gsub(/\\{FILE\\}/, file);
                                  gsub(/\\{ISSUES\\}/, issues);
                                  gsub(/\\{CURRENT_CONTENT\\}/, content);
                                  print}' \
                                "$TEMPLATE_FILE")

              echo "$FIX_PROMPT" > /tmp/fix_prompt.txt

              # Run Claude in safe mode (no --dangerously-skip-permissions)
              # Claude will suggest fixes but won't modify files directly
              if claude --model "${{ inputs.claude-model }}" < /tmp/fix_prompt.txt > /tmp/claude_fix.log 2>&1; then
                echo "  AI-powered fix completed for $file"
                # Note: In safe mode, suggestions are in claude_fix.log
                # Manual review and application required
              else
                echo "  AI-powered fix failed for $file. Check /tmp/claude_fix.log"
              fi
            fi
          else
            echo "  OK"
          fi
        done

        # Count total errors
        ERRORS=$(wc -l < /tmp/validation_errors.count 2>/dev/null || echo "0")

        # Output summary
        if [ $ERRORS -gt 0 ]; then
          echo "::error::Found $ERRORS file(s) with validation issues"
          echo "errors=$ERRORS" >> $GITHUB_OUTPUT
          if [ "${{ inputs.fail-on-error }}" = "true" ]; then
            exit 1
          fi
        else
          echo "All YAML files are valid!"
          echo "errors=0" >> $GITHUB_OUTPUT
        fi

    - name: Commit auto-fixes
      if: inputs.auto-fix == 'true' && steps.validate.outputs.errors != '0'
      shell: bash
      run: |
        # Use centralized git user configuration with workflow traceability
        RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .github/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ inputs.commit-message }}" -m "Workflow: $RUN_URL"
          echo "Created commit with auto-fixes"
        fi

    - name: Create PR for fixes
      if: inputs.auto-fix == 'true'
      shell: bash
      run: |
        if ! git diff --quiet origin/main...HEAD 2>/dev/null; then
          BRANCH="action-fixer-auto-$(date +%s)"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"

          # Create PR body
          PR_BODY="This PR was automatically created by GitHub Actions Fixer to resolve workflow validation issues.

          **Changes:**
          - Fixed YAML validation commands
          - Corrected syntax errors

          Please review the changes before merging."

          gh pr create \
            --title "fix: automated workflow validation fixes" \
            --body "$PR_BODY" \
            --base main
        fi
