name: 'AI Review and Fix'
description: 'Review and automatically fix code issues using Claude Code CLI.'
inputs:
  github-token:
    description: 'GitHub token for API operations'
    required: false
    default: ${{ github.token }}
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  lgtm-threshold:
    description: 'Minimum confidence score for LGTM (1-10, default: 7)'
    required: false
    default: '7'
  review-prompt-template:
    description: 'Path to custom review prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  comment-template:
    description: 'Path to custom comment template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  custom-rules:
    description: 'Additional rules or guidelines for the review'
    required: false
    default: ''
  auto-fix:
    description: 'Whether to automatically fix issues found in the review (default: true)'
    required: false
    default: 'true'
outputs:
  verdict:
    description: 'Review verdict (LGTM or REQUEST_CHANGES)'
    value: ${{ steps.review.outputs.verdict }}
  confidence:
    description: 'Confidence score (1-10)'
    value: ${{ steps.review.outputs.confidence }}
runs:
  using: 'composite'
  steps:
    - name: Checkout PR
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Checking out PR #$PR_NUMBER"
        gh pr checkout $PR_NUMBER

    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching PR diff..."
        gh pr diff $PR_NUMBER > /tmp/pr_diff.patch
        echo "diff_size=$(wc -c < /tmp/pr_diff.patch)" >> $GITHUB_OUTPUT
        echo "PR diff saved to /tmp/pr_diff.patch"

    - name: Review or Fix with Claude Code CLI
      shell: bash
      id: review
      run: |
        ${{ github.action_path }}/scripts/review-and-fix.sh \
          "${{ github.event.pull_request.number }}" \
          "${{ inputs.claude-model }}" \
          "${{ inputs.lgtm-threshold }}" \
          "${{ inputs.review-prompt-template }}" \
          "${{ inputs.custom-rules }}" \
          "${{ inputs.auto-fix }}" \
          "${{ inputs.comment-template }}"

    - name: Post review comment
      shell: bash
      if: always() && inputs.auto-fix != 'true'
      run: |
        ${{ github.action_path }}/scripts/post-comment.sh \
          "${{ github.event.pull_request.number }}" \
          "${{ steps.review.outputs.verdict }}" \
          "${{ steps.review.outputs.confidence }}" \
          "${{ steps.review.outputs.summary }}" \
          "${{ inputs.lgtm-threshold }}" \
          "${{ inputs.comment-template }}" \
          "${{ inputs.claude-model }}"