name: 'AI Review and Fix'
description: 'Review and automatically fix code issues using Claude Code CLI.'
inputs:
  github-token:
    description: 'GitHub token with repo permissions'
    required: true
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  lgtm-threshold:
    description: 'Minimum confidence score for LGTM (1-10, default: 7)'
    required: false
    default: '7'
  review-prompt-template:
    description: 'Path to custom review prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  comment-template:
    description: 'Path to custom comment template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  custom-rules:
    description: 'Additional rules or guidelines for the review'
    required: false
    default: ''
  auto-fix:
    description: 'Whether to automatically fix issues found in the review (default: true)'
    required: false
    default: 'true'
outputs:
  verdict:
    description: 'Review verdict (LGTM or REQUEST_CHANGES)'
    value: ${{ steps.review.outputs.verdict }}
  confidence:
    description: 'Confidence score (1-10)'
    value: ${{ steps.review.outputs.confidence }}
runs:
  using: 'composite'
  steps:
    - name: Checkout PR
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Checking out PR #$PR_NUMBER"
        gh pr checkout $PR_NUMBER

    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching PR diff..."
        gh pr diff $PR_NUMBER > /tmp/pr_diff.patch
        echo "diff_size=$(wc -c < /tmp/pr_diff.patch)" >> $GITHUB_OUTPUT
        echo "PR diff saved to /tmp/pr_diff.patch"

    - name: Review or Fix with Claude Code CLI
      shell: bash
      id: review
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        MODEL="${{ inputs.claude-model }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        REVIEW_PROMPT_TEMPLATE="${{ inputs.review-prompt-template }}"
        CUSTOM_RULES="${{ inputs.custom-rules }}"
        AUTO_FIX="${{ inputs.auto-fix }}"

        echo "Running Claude Code CLI..."
        echo "Model: $MODEL"
        echo "Auto Fix: $AUTO_FIX"

        if [ "$AUTO_FIX" = "true" ]; then
          # --- AUTO FIX MODE ---
          echo "Entering Auto-Fix mode..."
          TEMPLATE_FILE="${{ github.action_path }}/templates/fix_prompt.txt"
          cat "$TEMPLATE_FILE" > /tmp/fix_prompt.txt
          
          if [ -n "$CUSTOM_RULES" ]; then
            echo -e "\nAdditional Rules:\n$CUSTOM_RULES" >> /tmp/fix_prompt.txt
          fi
          
          echo '' >> /tmp/fix_prompt.txt
          cat /tmp/pr_diff.patch >> /tmp/fix_prompt.txt

          if claude --dangerously-skip-permissions --model "$MODEL" < /tmp/fix_prompt.txt > /tmp/claude_output.txt 2>&1; then
             echo "Claude fix execution completed"
          else
             echo "Claude execution failed"
             exit 1
          fi

          if git diff --quiet; then
            echo "No changes made by Claude."
            SUMMARY="Analyzed code, no fixes needed."
            MADE_CHANGES="false"
          else
            echo "Changes detected. Committing..."
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git add .
            git commit -m "fix: auto-correction by Claude Code"
            git push
            SUMMARY="Applied auto-fixes based on code analysis."
            MADE_CHANGES="true"
          fi
          
          VERDICT="LGTM"
          CONFIDENCE="10"
          
        else
          # --- REVIEW MODE ---
          echo "Entering Review mode..."
          if [ -n "$REVIEW_PROMPT_TEMPLATE" ] && [ -f "$REVIEW_PROMPT_TEMPLATE" ]; then
            REVIEW_PROMPT_FILE="$REVIEW_PROMPT_TEMPLATE"
          else
            REVIEW_PROMPT_FILE="${{ github.action_path }}/templates/review_prompt.txt"
          fi

          cat "$REVIEW_PROMPT_FILE" > /tmp/review_prompt.txt
          
          if [ -n "$CUSTOM_RULES" ]; then
            echo -e "\nAdditional Rules for this Review:\n$CUSTOM_RULES" >> /tmp/review_prompt.txt
          fi

          echo '' >> /tmp/review_prompt.txt
          cat /tmp/pr_diff.patch >> /tmp/review_prompt.txt

          if claude --dangerously-skip-permissions --model "$MODEL" < /tmp/review_prompt.txt > /tmp/claude_response.json 2>&1; then
            echo "Claude review completed"
          else
            echo '{"verdict":"REQUEST_CHANGES","confidence":1,"summary":"Claude CLI error"}' > /tmp/claude_response.json
          fi

          if grep -q '"verdict"[[:space:]]*:[[:space:]]*"LGTM"' /tmp/claude_response.json; then
            VERDICT="LGTM"
          else
            VERDICT="REQUEST_CHANGES"
          fi
          CONFIDENCE=$(grep -oP '"confidence"[[:space:]]*:[[:space:]]*\K\d+' /tmp/claude_response.json || echo "1")
          SUMMARY=$(grep -oP '"summary"[[:space:]]*:[[:space:]]*"\K[^"].*' /tmp/claude_response.json || echo "No summary")
          MADE_CHANGES="false"
        fi

        echo "verdict=$VERDICT" >> $GITHUB_OUTPUT
        echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT
        echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
        echo "made_changes=$MADE_CHANGES" >> $GITHUB_OUTPUT

    - name: Post review comment
      shell: bash
      if: always() && inputs.auto-fix != 'true'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        VERDICT="${{ steps.review.outputs.verdict }}"
        CONFIDENCE="${{ steps.review.outputs.confidence }}"
        SUMMARY="${{ steps.review.outputs.summary }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        COMMENT_TEMPLATE="${{ inputs.comment-template }}"

        if [ -n "$COMMENT_TEMPLATE" ] && [ -f "$COMMENT_TEMPLATE" ]; then
          TEMPLATE_FILE="$COMMENT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/comment_template.txt"
        fi

        if [ "$VERDICT" = "LGTM" ] && [ "$CONFIDENCE" -ge "$THRESHOLD" ]; then
          STATUS_MESSAGE="✅ This PR meets the LGTM threshold."
        else
          STATUS_MESSAGE="❌ This PR requires changes."
        fi

        COMMENT=$(sed -e "s#{VERDICT}#$VERDICT#g" \
                      -e "s#{CONFIDENCE}#$CONFIDENCE#g" \
                      -e "s#{THRESHOLD}#$THRESHOLD#g" \
                      -e "s#{SUMMARY}#$SUMMARY#g" \
                      -e "s#{STATUS_MESSAGE}#$STATUS_MESSAGE#g" \
                      -e "s#{MODEL}#${{ inputs.claude-model }}#g" \
                      "$TEMPLATE_FILE")

        gh pr comment $PR_NUMBER --body "$COMMENT"