name: 'Review PR and Auto-Merge'
description: 'Automatically fix code issues using Claude Code CLI and merge the PR.'
inputs:
  github-token:
    description: 'GitHub token with repo permissions'
    required: true
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  lgtm-threshold:
    description: 'Minimum confidence score for LGTM (1-10, default: 7)'
    required: false
    default: '7'
  merge-method:
    description: 'Merge method (squash, merge, rebase)'
    required: false
    default: 'squash'
  review-prompt-template:
    description: 'Path to custom review prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  comment-template:
    description: 'Path to custom comment template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  custom-rules:
    description: 'Additional rules or guidelines for the review'
    required: false
    default: ''
  auto-fix:
    description: 'Whether to automatically fix issues found in the review (default: true)'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Checkout PR
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Checking out PR #$PR_NUMBER"
        gh pr checkout $PR_NUMBER

    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching PR diff..."
        gh pr diff $PR_NUMBER > /tmp/pr_diff.patch
        echo "diff_size=$(wc -c < /tmp/pr_diff.patch)" >> $GITHUB_OUTPUT
        echo "PR diff saved to /tmp/pr_diff.patch"

    - name: Review or Fix with Claude Code CLI
      shell: bash
      id: review
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        MODEL="${{ inputs.claude-model }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        REVIEW_PROMPT_TEMPLATE="${{ inputs.review-prompt-template }}"
        CUSTOM_RULES="${{ inputs.custom-rules }}"
        AUTO_FIX="${{ inputs.auto-fix }}"

        echo "Running Claude Code CLI..."
        echo "Model: $MODEL"
        echo "Auto Fix: $AUTO_FIX"

        if [ "$AUTO_FIX" = "true" ]; then
          # --- AUTO FIX MODE ---
          echo "Entering Auto-Fix mode..."
          
          # Use fix prompt template
          TEMPLATE_FILE="${{ github.action_path }}/templates/fix_prompt.txt"
          
          cat "$TEMPLATE_FILE" > /tmp/fix_prompt.txt
          
          if [ -n "$CUSTOM_RULES" ]; then
            echo -e "\nAdditional Rules:\n$CUSTOM_RULES" >> /tmp/fix_prompt.txt
          fi
          
          echo '' >> /tmp/fix_prompt.txt
          cat /tmp/pr_diff.patch >> /tmp/fix_prompt.txt

          # Run Claude to FIX files
          # Not redirecting to json, letting it edit files
          if claude --dangerously-skip-permissions --model "$MODEL" < /tmp/fix_prompt.txt > /tmp/claude_output.txt 2>&1; then
             echo "Claude fix execution completed"
          else
             echo "Claude execution failed"
             exit 1
          fi

          # Check for changes
          if git diff --quiet; then
            echo "No changes made by Claude."
            SUMMARY="Analyzed code, no fixes needed."
          else
            echo "Changes detected. Committing..."
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git add .
            git commit -m "fix: auto-correction by Claude Code"
            git push
            SUMMARY="Applied auto-fixes based on code analysis."
          fi
          
          # In auto-fix mode, we assume LGTM if execution succeeded
          VERDICT="LGTM"
          CONFIDENCE="10"
          
        else
          # --- REVIEW MODE ---
          echo "Entering Review mode..."

          # Use custom template if provided, otherwise use built-in
          if [ -n "$REVIEW_PROMPT_TEMPLATE" ] && [ -f "$REVIEW_PROMPT_TEMPLATE" ]; then
            REVIEW_PROMPT_FILE="$REVIEW_PROMPT_TEMPLATE"
          else
            REVIEW_PROMPT_FILE="${{ github.action_path }}/templates/review_prompt.txt"
          fi

          cat "$REVIEW_PROMPT_FILE" > /tmp/review_prompt.txt
          
          if [ -n "$CUSTOM_RULES" ]; then
            echo -e "\nAdditional Rules for this Review:\n$CUSTOM_RULES" >> /tmp/review_prompt.txt
          fi

          echo '' >> /tmp/review_prompt.txt
          cat /tmp/pr_diff.patch >> /tmp/review_prompt.txt

          if claude --dangerously-skip-permissions --model "$MODEL" < /tmp/review_prompt.txt > /tmp/claude_response.json 2>&1; then
            echo "Claude review completed"
          else
            echo '{"verdict":"REQUEST_CHANGES","confidence":1,"summary":"Claude CLI error"}' > /tmp/claude_response.json
          fi

          # Parse JSON response
          if grep -q '"verdict"[[:space:]]*:[[:space:]]*"LGTM"' /tmp/claude_response.json; then
            VERDICT="LGTM"
          else
            VERDICT="REQUEST_CHANGES"
          fi
          CONFIDENCE=$(grep -oP '"confidence"[[:space:]]*:[[:space:]]*\K\d+' /tmp/claude_response.json || echo "1")
          SUMMARY=$(grep -oP '"summary"[[:space:]]*:[[:space:]]*"\K[^"].*' /tmp/claude_response.json || echo "No summary")
        fi

        echo "verdict=$VERDICT" >> $GITHUB_OUTPUT
        echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT
        echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

    - name: Post review comment
      shell: bash
      if: always() && inputs.auto-fix != 'true'
      run: |
        # Only post detailed comments in Review Mode
        PR_NUMBER=${{ github.event.pull_request.number }}
        VERDICT="${{ steps.review.outputs.verdict }}"
        CONFIDENCE="${{ steps.review.outputs.confidence }}"
        SUMMARY="${{ steps.review.outputs.summary }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        COMMENT_TEMPLATE="${{ inputs.comment-template }}"

        if [ -n "$COMMENT_TEMPLATE" ] && [ -f "$COMMENT_TEMPLATE" ]; then
          TEMPLATE_FILE="$COMMENT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/comment_template.txt"
        fi

        if [ "$VERDICT" = "LGTM" ] && [ "$CONFIDENCE" -ge "$THRESHOLD" ]; then
          STATUS_MESSAGE="✅ This PR meets the LGTM threshold and will be auto-merged."
        else
          STATUS_MESSAGE="❌ This PR does not meet the LGTM threshold or requires changes."
        fi

        COMMENT=$(sed -e "s#{VERDICT}#$VERDICT#g" \
                      -e "s#{CONFIDENCE}#$CONFIDENCE#g" \
                      -e "s#{THRESHOLD}#$THRESHOLD#g" \
                      -e "s#{SUMMARY}#$SUMMARY#g" \
                      -e "s#{STATUS_MESSAGE}#$STATUS_MESSAGE#g" \
                      -e "s#{MODEL}#${{ inputs.claude-model }}#g" \
                      "$TEMPLATE_FILE")

        gh pr comment $PR_NUMBER --body "$COMMENT"

    - name: Rebase if needed before merge
      shell: bash
      if: steps.review.outputs.verdict == 'LGTM' && steps.review.outputs.confidence >= inputs.lgtm-threshold
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        MERGE_METHOD="${{ inputs.merge-method }}"
        BASE_BRANCH="${{ github.event.pull_request.base.ref_name }}"

        echo "Checking if rebase is needed..."
        # Fetch latest base branch
        git fetch origin "$BASE_BRANCH"

        # Check if branch is behind base
        BEHIND_COUNT=$(git rev-list --count HEAD..origin/"$BASE_BRANCH" 2>/dev/null || echo "0")

        if [ "$BEHIND_COUNT" -gt 0 ]; then
          echo "Branch is $BEHIND commits behind $BASE_BRANCH. Rebasing..."

          # Attempt rebase
          if git rebase origin/"$BASE_BRANCH"; then
            echo "Rebase successful. Force pushing..."
            git push --force-with-lease
          else
            echo "Rebase failed. Attempting to resolve conflicts..."

            # Check if there are conflicts
            if ! git diff --quiet; then
              echo "Conflicts detected. Attempting automatic resolution..."

              # Try to resolve using 'theirs' for conflicts (prefer base branch changes)
              # This is a conservative approach - can be customized
              git diff --name-only --diff-filter=U | while read -r file; do
                echo "Found conflict in: $file"
                # Checkout the base branch version for conflict files
                git checkout --theirs "$file" 2>/dev/null || git checkout --ours "$file"
                git add "$file"
              done

              # Continue rebase after resolution
              if git rebase --continue; then
                echo "Conflicts resolved. Committing and pushing..."
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git config user.name "github-actions[bot]"
                git push --force-with-lease
              else
                echo "Failed to resolve conflicts automatically. Aborting rebase."
                git rebase --abort 2>/dev/null || true
                echo "::warning::Could not automatically resolve merge conflicts. Manual intervention required."
                exit 1
              fi
            else
              echo "Rebase failed for unknown reason. Aborting."
              git rebase --abort 2>/dev/null || true
              exit 1
            fi
          fi
        else
          echo "Branch is up to date with $BASE_BRANCH. No rebase needed."
        fi

    - name: Merge PR if LGTM
      shell: bash
      if: steps.review.outputs.verdict == 'LGTM' && steps.review.outputs.confidence >= inputs.lgtm-threshold
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        MERGE_METHOD="${{ inputs.merge-method }}"

        echo "Merging PR #$PR_NUMBER using $MERGE_METHOD merge..."

        case "$MERGE_METHOD" in
          squash)
            gh pr merge $PR_NUMBER --squash --delete-branch --subject "Auto-merge after LGTM review"
            ;;
          merge)
            gh pr merge $PR_NUMBER --merge --delete-branch
            ;;
          rebase)
            gh pr merge $PR_NUMBER --rebase --delete-branch
            ;;
        esac

        echo "PR merged successfully"