name: 'Review PR and Auto-Merge'
description: 'Review a PR using Claude Code CLI and merge if LGTM'
inputs:
  github-token:
    description: 'GitHub token with repo permissions'
    required: true
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  lgtm-threshold:
    description: 'Minimum confidence score for LGTM (1-10, default: 7)'
    required: false
    default: '7'
  merge-method:
    description: 'Merge method (squash, merge, rebase)'
    required: false
    default: 'squash'
  review-prompt-template:
    description: 'Path to custom review prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  comment-template:
    description: 'Path to custom comment template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  custom-rules:
    description: 'Additional rules or guidelines for the review'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout PR
      shell: bash
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Checking out PR #$PR_NUMBER"
        gh pr checkout $PR_NUMBER

    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Fetching PR diff..."
        gh pr diff $PR_NUMBER > /tmp/pr_diff.patch
        echo "diff_size=$(wc -c < /tmp/pr_diff.patch)" >> $GITHUB_OUTPUT
        echo "PR diff saved to /tmp/pr_diff.patch"

    - name: Review with Claude Code CLI
      shell: bash
      id: review
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        MODEL="${{ inputs.claude-model }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        REVIEW_PROMPT_TEMPLATE="${{ inputs.review-prompt-template }}"
        CUSTOM_RULES="${{ inputs.custom-rules }}"

        echo "Running Claude Code CLI review..."
        echo "Model: $MODEL"
        echo "LGTM Threshold: $THRESHOLD/10"

        # Use custom template if provided, otherwise use built-in
        if [ -n "$REVIEW_PROMPT_TEMPLATE" ] && [ -f "$REVIEW_PROMPT_TEMPLATE" ]; then
          echo "Using custom review prompt template: $REVIEW_PROMPT_TEMPLATE"
          REVIEW_PROMPT_FILE="$REVIEW_PROMPT_TEMPLATE"
        else
          REVIEW_PROMPT_FILE="${{ github.action_path }}/templates/review_prompt.txt"
        fi

        # Create review prompt from template
        cat "$REVIEW_PROMPT_FILE" > /tmp/review_prompt.txt
        
        # Inject custom rules if provided
        if [ -n "$CUSTOM_RULES" ]; then
          echo -e "\nAdditional Rules for this Review:\n$CUSTOM_RULES" >> /tmp/review_prompt.txt
        fi

        echo '' >> /tmp/review_prompt.txt

        # Append PR diff
        cat /tmp/pr_diff.patch >> /tmp/review_prompt.txt

        # Run Claude Code CLI
        if claude --dangerously-skip-permissions --model "$MODEL" < /tmp/review_prompt.txt > /tmp/claude_response.json 2>&1; then
          echo "Claude review completed"
        else
          echo "Claude CLI failed, using fallback"
          echo '{"verdict":"REQUEST_CHANGES","confidence":1,"summary":"Claude CLI error","issues":["Claude Code CLI failed to execute"]}' > /tmp/claude_response.json
        fi

        # Parse response (simple extraction)
        if grep -q '"verdict"[[:space:]]*:[[:space:]]*"LGTM"' /tmp/claude_response.json; then
          VERDICT="LGTM"
        else
          VERDICT="REQUEST_CHANGES"
        fi

        # Extract confidence (default to 1 if not found)
        CONFIDENCE=$(grep -oP '"confidence"[[:space:]]*:[[:space:]]*\K\d+' /tmp/claude_response.json || echo "1")

        # Extract summary
        SUMMARY=$(grep -oP '"summary"[[:space:]]*:[[:space:]]*"\K[^"]*' /tmp/claude_response.json || echo "No summary")

        echo "verdict=$VERDICT" >> $GITHUB_OUTPUT
        echo "confidence=$CONFIDENCE" >> $GITHUB_OUTPUT
        echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

        # Save full response for comment
        cp /tmp/claude_response.json /tmp/review_result.json

        echo "Review Verdict: $VERDICT"
        echo "Confidence: $CONFIDENCE/$THRESHOLD"

    - name: Post review comment
      shell: bash
      if: always()
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        VERDICT="${{ steps.review.outputs.verdict }}"
        CONFIDENCE="${{ steps.review.outputs.confidence }}"
        SUMMARY="${{ steps.review.outputs.summary }}"
        THRESHOLD="${{ inputs.lgtm-threshold }}"
        COMMENT_TEMPLATE="${{ inputs.comment-template }}"

        # Use custom template if provided, otherwise use built-in
        if [ -n "$COMMENT_TEMPLATE" ] && [ -f "$COMMENT_TEMPLATE" ]; then
          echo "Using custom comment template: $COMMENT_TEMPLATE"
          TEMPLATE_FILE="$COMMENT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/comment_template.txt"
        fi

        # Determine status message
        if [ "$VERDICT" = "LGTM" ] && [ "$CONFIDENCE" -ge "$THRESHOLD" ]; then
          STATUS_MESSAGE="✅ This PR meets the LGTM threshold and will be auto-merged."
        else
          STATUS_MESSAGE="❌ This PR does not meet the LGTM threshold or requires changes."
        fi

        # Create comment from template
        COMMENT=$(sed -e "s#{VERDICT}#$VERDICT#g" \
                      -e "s#{CONFIDENCE}#$CONFIDENCE#g" \
                      -e "s#{THRESHOLD}#$THRESHOLD#g" \
                      -e "s#{SUMMARY}#$SUMMARY#g" \
                      -e "s#{STATUS_MESSAGE}#$STATUS_MESSAGE#g" \
                      -e "s#{MODEL}#${{ inputs.claude-model }}#g" \
                      "$TEMPLATE_FILE")

        gh pr comment $PR_NUMBER --body "$COMMENT"

    - name: Merge PR if LGTM
      shell: bash
      if: steps.review.outputs.verdict == 'LGTM' && steps.review.outputs.confidence >= inputs.lgtm-threshold
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        MERGE_METHOD="${{ inputs.merge-method }}"

        echo "Merging PR #$PR_NUMBER using $MERGE_METHOD merge..."

        case "$MERGE_METHOD" in
          squash)
            gh pr merge $PR_NUMBER --squash --delete-branch --subject "Auto-merge after LGTM review"
            ;;
          merge)
            gh pr merge $PR_NUMBER --merge --delete-branch
            ;;
          rebase)
            gh pr merge $PR_NUMBER --rebase --delete-branch
            ;;
        esac

        echo "PR merged successfully"
