name: Scheduled PR Review Enqueue

# Run every 3 hours to scan and enqueue PRs for review
on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:  # Allow manual trigger

permissions:
  pull-requests: write  # For adding /review comments
  contents: read

jobs:
  enqueue-prs-for-review:
    name: Scan and Enqueue PRs
    runs-on: self-hosted

    steps:
      - name: Enqueue all open PRs for review
        uses: ./actions/pr-review-enqueuer  # Replace with your-org/github-actions-actions/actions/pr-review-enqueuer@v1 after publishing
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Process all open PRs (including drafts and WIP)
          pr-filter: 'all'
          # No label filter - process all PRs
          label-filter: ''
          # Only process PRs older than 5 minutes (avoid race with PR creation)
          age-threshold: '5'
          # Skip already merged/closed PRs
          exclude-labels: 'auto-merged,merged,closed'
          # Process unlimited PRs per run
          batch-size: '0'
          dry-run: 'false'
