name: Generate AI Release Notes

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AI Release Notes
        uses: ./actions/release-notes-ai
        with:
          base-ref: 'main'
          head-ref: ${{ github.ref_name }}
          output-file: 'RELEASE_NOTES.md'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release with notes
        run: |
          gh release edit ${{ github.ref_name }} --notes-file RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
