# AI Review and Auto-Merge Workflow Example
#
# This workflow demonstrates automated PR review and merging using Claude Code CLI.
# Place this file at: .github/workflows/review-auto-merge.yml
#
# Features:
# - AI-powered code review with auto-fix
# - CI status verification
# - Automatic merging on success
# - Retry logic for merge failures
#
# Requirements:
# - Self-hosted runner with Claude Code CLI installed

name: AI Review and Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Ensure only one workflow runs at a time per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  # AI Review and Auto-fix using Claude Code CLI
  ai-review:
    runs-on: self-hosted
    outputs:
      verdict: ${{ steps.review.outputs.verdict }}
      confidence: ${{ steps.review.outputs.confidence }}
      made-changes: ${{ steps.review.outputs.made_changes }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: AI Review and Fix
        id: review
        uses: ./actions/review-and-merge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          claude-model: sonnet
          auto-fix: 'true'
          lgtm-threshold: '7'

  # Wait for CI checks to complete
  wait-for-ci:
    runs-on: ubuntu-latest
    needs: ai-review

    steps:
      - name: Wait for CI checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "### Waiting for CI checks to complete" >> $GITHUB_STEP_SUMMARY

          # Wait up to 30 minutes for CI
          TIMEOUT=1800  # 30 minutes in seconds
          ELAPSED=0
          CHECK_INTERVAL=30  # Check every 30 seconds

          while [ $ELAPSED -lt $TIMEOUT ]; do
            # Get all check runs for the PR
            CHECKS=$(gh pr checks "$PR_NUMBER" --json name,conclusion --jq '.[]' 2>/dev/null || echo "")

            # Check if all non-skipped checks are completed
            PENDING=$(echo "$CHECKS" | jq -r 'select(.conclusion == null) // empty' | wc -l)

            if [ "$PENDING" -eq 0 ]; then
              echo "✅ All CI checks completed" >> $GITHUB_STEP_SUMMARY

              # Check if any failed
              FAILED=$(echo "$CHECKS" | jq -r 'select(.conclusion == "failure") // empty' | wc -l)
              if [ "$FAILED" -gt 0 ]; then
                echo "⚠️ Some CI checks failed" >> $GITHUB_STEP_SUMMARY
                echo "failed_checks=true" >> $GITHUB_ENV
              else
                echo "All checks passed" >> $GITHUB_STEP_SUMMARY
                echo "failed_checks=false" >> $GITHUB_ENV
              fi
              break
            fi

            echo "Waiting for $PENDING checks to complete... ($(($ELAPSED / 60))m elapsed)" >> $GITHUB_STEP_SUMMARY
            sleep $CHECK_INTERVAL
            ELAPSED=$((ELAPSED + CHECK_INTERVAL))
          done

          if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "⚠️ Timeout waiting for CI checks" >> $GITHUB_STEP_SUMMARY
            echo "failed_checks=true" >> $GITHUB_ENV
          fi

  # Auto-merge PR if review and CI pass
  auto-merge:
    runs-on: ubuntu-latest
    needs: [ai-review, wait-for-ci]
    if: |
      always() &&
      needs.ai-review.result == 'success' &&
      needs.wait-for-ci.result == 'success'

    steps:
      - name: Attempt merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          VERDICT: ${{ needs.ai-review.outputs.verdict }}
          CONFIDENCE: ${{ needs.ai-review.outputs.confidence }}
          MADE_CHANGES: ${{ needs.ai-review.outputs.made-changes }}
          FAILED_CHECKS: ${{ needs.wait-for-ci.outputs.failed_checks }}
        run: |
          echo "### Attempting to merge PR #$PR_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "- Verdict: $VERDICT" >> $GITHUB_STEP_SUMMARY
          echo "- Confidence: $CONFIDENCE" >> $GITHUB_STEP_SUMMARY
          echo "- Made changes: $MADE_CHANGES" >> $GITHUB_STEP_SUMMARY
          echo "- CI failed: $FAILED_CHECKS" >> $GITHUB_STEP_SUMMARY

          # Only merge if LGTM, CI passed, and no changes were made (auto-fix already pushed)
          if [ "$VERDICT" = "LGTM" ] && [ "$FAILED_CHECKS" = "false" ]; then
            echo "✅ Conditions met for auto-merge" >> $GITHUB_STEP_SUMMARY

            # Retry logic
            MAX_ATTEMPTS=10
            ATTEMPT=1
            MERGE_METHODS=("squash" "merge" "rebase")

            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "Attempt $ATTEMPT of $MAX_ATTEMPTS" >> $GITHUB_STEP_SUMMARY

              # Check if PR is still open
              PR_STATE=$(gh pr view "$PR_NUMBER" --json state -q '.state')
              if [ "$PR_STATE" != "open" ]; then
                echo "PR is no longer open (state: $PR_STATE)" >> $GITHUB_STEP_SUMMARY
                exit 0
              fi

              # Try each merge method
              for METHOD in "${MERGE_METHODS[@]}"; do
                case $METHOD in
                  squash)
                    if gh pr merge "$PR_NUMBER" --squash --delete-branch 2>/dev/null; then
                      echo "✅ Merged using squash" >> $GITHUB_STEP_SUMMARY
                      exit 0
                    fi
                    ;;
                  merge)
                    if gh pr merge "$PR_NUMBER" --merge --delete-branch 2>/dev/null; then
                      echo "✅ Merged using merge commit" >> $GITHUB_STEP_SUMMARY
                      exit 0
                    fi
                    ;;
                  rebase)
                    if gh pr merge "$PR_NUMBER" --rebase --delete-branch 2>/dev/null; then
                      echo "✅ Merged using rebase" >> $GITHUB_STEP_SUMMARY
                      exit 0
                    fi
                    ;;
                esac
              done

              ATTEMPT=$((ATTEMPT + 1))
              if [ $ATTEMPT -le $MAX_ATTEMPTS ]; then
                sleep 5
              fi
            done

            echo "❌ Failed to merge after $MAX_ATTEMPTS attempts" >> $GITHUB_STEP_SUMMARY
            gh pr comment "$PR_NUMBER" --body "❌ **Auto-merge failed after retry**

            Tried $MAX_ATTEMPTS attempts with all merge methods (squash, merge, rebase).
            Manual intervention may be needed."
            exit 1
          else
            echo "⏸️ Conditions not met for auto-merge" >> $GITHUB_STEP_SUMMARY
            echo "Review verdict: $VERDICT, CI failed: $FAILED_CHECKS" >> $GITHUB_STEP_SUMMARY
          fi
