name: 'AI Release Notes'
description: 'Generate high-quality release notes from commit history using Claude Code CLI'
inputs:
  base-ref:
    description: 'Base reference (e.g., previous tag or main)'
    required: false
    default: 'main'
  head-ref:
    description: 'Head reference (e.g., current branch or tag)'
    required: false
    default: 'HEAD'
  output-file:
    description: 'File to save the release notes to'
    required: false
    default: 'RELEASE_NOTES.md'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  release-prompt-template:
    description: 'Path to custom release prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API operations'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Generate Release Notes with Claude Code CLI
      shell: bash
      run: |
        BASE="${{ inputs.base-ref }}"
        HEAD="${{ inputs.head-ref }}"
        OUTPUT="${{ inputs.output-file }}"
        MODEL="${{ inputs.claude-model }}"
        RELEASE_PROMPT_TEMPLATE="${{ inputs.release-prompt-template }}"

        echo "Generating release notes from $BASE to $HEAD..."

        # Collect commit logs
        GIT_LOG=$(git log "$BASE..$HEAD" --oneline --no-merges)
        # Collect merged PRs
        PRS=$(gh pr list --base main --state merged --json title,number,author -L 50)

        # Use custom template if provided, otherwise use built-in
        if [ -n "$RELEASE_PROMPT_TEMPLATE" ]; then
          # Validate path to prevent directory traversal
          if [[ "$RELEASE_PROMPT_TEMPLATE" == *".."*"."* ]] || [[ "$RELEASE_PROMPT_TEMPLATE" == *"/"*".."* ]]; then
            echo "::error::Path traversal detected in template path"
            exit 1
          fi
          # Resolve to absolute path and ensure it's within allowed directories
          RESOLVED_PATH=$(cd "$GITHUB_WORKSPACE" 2>/dev/null && cd "$(dirname "$RELEASE_PROMPT_TEMPLATE")" 2>/dev/null && pwd)/$(basename "$RELEASE_PROMPT_TEMPLATE") 2>/dev/null || echo ""
          if [ -z "$RESOLVED_PATH" ] || [[ ! "$RESOLVED_PATH" == "$GITHUB_WORKSPACE"* ]] && [[ ! "$RESOLVED_PATH" == "${{ github.action_path }}"* ]]; then
            echo "::error::Template path must be within workspace or action directory"
            exit 1
          fi
          if [ -f "$RESOLVED_PATH" ]; then
            TEMPLATE_FILE="$RESOLVED_PATH"
          else
            echo "::error::Template file not found: $RELEASE_PROMPT_TEMPLATE"
            exit 1
          fi
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/release_prompt.txt"
        fi

        # Read template and replace placeholders safely using awk
        RELEASE_PROMPT=$(awk -v git_log="$GIT_LOG" \
                             -v prs="$PRS" \
                             -v output="$OUTPUT" \
                             '{
                               gsub(/\{GIT_LOG\}/, git_log)
                               gsub(/\{PRS\}/, prs)
                               gsub(/\{OUTPUT\}/, output)
                               print
                             }' "$TEMPLATE_FILE")

        echo "$RELEASE_PROMPT" > /tmp/release_prompt.txt

        # Check Claude CLI availability before invoking
        if ! command -v claude &> /dev/null; then
          echo "::error::Claude CLI not found. Please install Claude CLI first."
          echo "  Visit https://claude.ai/ for installation instructions."
          exit 1
        fi

        # Run Claude in safe mode (no --dangerously-skip-permissions)
        claude --model "$MODEL" < /tmp/release_prompt.txt
