name: 'AI Release Notes'
description: 'Generate high-quality release notes from commit history using Claude Code CLI'
inputs:
  base-ref:
    description: 'Base reference (e.g., previous tag or main)'
    required: false
    default: 'main'
  head-ref:
    description: 'Head reference (e.g., current branch or tag)'
    required: false
    default: 'HEAD'
  output-file:
    description: 'File to save the release notes to'
    required: false
    default: 'RELEASE_NOTES.md'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  release-prompt-template:
    description: 'Path to custom release prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate Release Notes with Claude Code CLI
      shell: bash
      run: |
        BASE="${{ inputs.base-ref }}"
        HEAD="${{ inputs.head-ref }}"
        OUTPUT="${{ inputs.output-file }}"
        MODEL="${{ inputs.claude-model }}"
        RELEASE_PROMPT_TEMPLATE="${{ inputs.release-prompt-template }}"

        echo "Generating release notes from $BASE to $HEAD..."

        # Collect commit logs
        GIT_LOG=$(git log "$BASE..$HEAD" --oneline --no-merges)
        # Collect merged PRs
        PRS=$(gh pr list --base main --state merged --json title,number,author -L 50)

        # Use custom template if provided, otherwise use built-in
        if [ -n "$RELEASE_PROMPT_TEMPLATE" ] && [ -f "$RELEASE_PROMPT_TEMPLATE" ]; then
          TEMPLATE_FILE="$RELEASE_PROMPT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/release_prompt.txt"
        fi

        # Read template and replace placeholders
        RELEASE_PROMPT=$(sed -e "s/{GIT_LOG}/$GIT_LOG/g" \
                              -e "s/{PRS}/$PRS/g" \
                              -e "s/{OUTPUT}/$OUTPUT/g" \
                              "$TEMPLATE_FILE")

        echo "$RELEASE_PROMPT" > /tmp/release_prompt.txt

        # Run Claude Code CLI
        claude --dangerously-skip-permissions --model "$MODEL" < /tmp/release_prompt.txt
