name: 'Auto Refactor'
description: 'Automatically refactor code using Claude Code CLI'
inputs:
  path:
    description: 'File or directory to refactor'
    required: true
  instruction:
    description: 'Specific refactoring instructions (e.g., "Use async/await", "Improve readability")'
    required: false
    default: 'Improve code quality, readability, and follow best practices.'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  refactor-prompt-template:
    description: 'Path to custom refactor prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Refactor with Claude Code CLI
      shell: bash
      run: |
        # Source shared validation functions
        source "${{ github.action_path }}/../_shared/scripts/validate-template-path.sh"

        TARGET_PATH="${{ inputs.path }}"
        INSTRUCTION="${{ inputs.instruction }}"
        MODEL="${{ inputs.claude-model }}"
        REFACTOR_PROMPT_TEMPLATE="${{ inputs.refactor-prompt-template }}"

        if [ ! -e "$TARGET_PATH" ]; then
          echo "::error::Target path not found: $TARGET_PATH"
          exit 1
        fi

        echo "Refactoring $TARGET_PATH with instructions: $INSTRUCTION"

        # Validate and resolve template path using shared function
        BUILTIN_TEMPLATE="${{ github.action_path }}/templates/refactor_prompt.txt"
        if ! validate_template_path "$REFACTOR_PROMPT_TEMPLATE" "$BUILTIN_TEMPLATE" TEMPLATE_FILE; then
          exit 1
        fi

        # Read template and replace placeholders safely using awk
        REFACTOR_PROMPT=$(awk -v target_path="$TARGET_PATH" \
                             -v instruction="$INSTRUCTION" \
                             '{
                               gsub(/\{TARGET_PATH\}/, target_path)
                               gsub(/\{INSTRUCTION\}/, instruction)
                               print
                             }' "$TEMPLATE_FILE")

        echo "$REFACTOR_PROMPT" > /tmp/refactor_prompt.txt

        # Check Claude CLI availability using shared function
        if ! check_claude_cli; then
          exit 1
        fi

        # Run Claude in safe mode (no --dangerously-skip-permissions)
        claude --model "$MODEL" < /tmp/refactor_prompt.txt

