name: 'Auto Refactor'
description: 'Automatically refactor code using Claude Code CLI'
inputs:
  path:
    description: 'File or directory to refactor'
    required: true
  instruction:
    description: 'Specific refactoring instructions (e.g., "Use async/await", "Improve readability")'
    required: false
    default: 'Improve code quality, readability, and follow best practices.'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  refactor-prompt-template:
    description: 'Path to custom refactor prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Refactor with Claude Code CLI
      shell: bash
      run: |
        TARGET_PATH="${{ inputs.path }}"
        INSTRUCTION="${{ inputs.instruction }}"
        MODEL="${{ inputs.claude-model }}"
        REFACTOR_PROMPT_TEMPLATE="${{ inputs.refactor-prompt-template }}"

        if [ ! -e "$TARGET_PATH" ]; then
          echo "::error::Target path not found: $TARGET_PATH"
          exit 1
        fi

        echo "Refactoring $TARGET_PATH with instructions: $INSTRUCTION"

        # Use custom template if provided, otherwise use built-in
        if [ -n "$REFACTOR_PROMPT_TEMPLATE" ] && [ -f "$REFACTOR_PROMPT_TEMPLATE" ]; then
          TEMPLATE_FILE="$REFACTOR_PROMPT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/refactor_prompt.txt"
        fi

        # Read template and replace placeholders safely using awk
        REFACTOR_PROMPT=$(awk -v target_path="$TARGET_PATH" \
                             -v instruction="$INSTRUCTION" \
                             '{
                               gsub(/\{TARGET_PATH\}/, target_path)
                               gsub(/\{INSTRUCTION\}/, instruction)
                               print
                             }' "$TEMPLATE_FILE")

        echo "$REFACTOR_PROMPT" > /tmp/refactor_prompt.txt

        # Run Claude in safe mode (no --dangerously-skip-permissions)
        claude --model "$MODEL" < /tmp/refactor_prompt.txt
