name: 'Spec to Code'
description: 'Generate code from Markdown specifications using Claude Code CLI'
inputs:
  spec-path:
    description: 'Path to the Markdown specification file'
    required: true
  output-dir:
    description: 'Directory where the code should be generated'
    required: false
    default: '.'
  language:
    description: 'Primary programming language (e.g., Python, TypeScript)'
    required: false
    default: 'TypeScript'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  gen-prompt-template:
    description: 'Path to custom generation prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Ensure output directory exists
      shell: bash
      run: mkdir -p ${{ inputs.output-dir }}

    - name: Generate Code with Claude Code CLI
      shell: bash
      run: |
        SPEC_PATH="${{ inputs.spec-path }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        LANG="${{ inputs.language }}"
        MODEL="${{ inputs.claude-model }}"
        GEN_PROMPT_TEMPLATE="${{ inputs.gen-prompt-template }}"

        # Resolve absolute paths within workspace (prevent path traversal)
        SPEC_PATH="$(cd "${GITHUB_WORKSPACE}/${{ inputs.spec-path }}" 2>/dev/null && pwd)/${{ inputs.spec-path }}"
        OUTPUT_DIR="$(cd "${GITHUB_WORKSPACE}/${{ inputs.output-dir }}" 2>/dev/null && pwd)/${{ inputs.output-dir }}"

        # Ensure paths are within workspace
        case "$SPEC_PATH" in
          "$GITHUB_WORKSPACE"*) ;;
          *) echo "::error::Spec path must be within repository: $SPEC_PATH"; exit 1 ;;
        esac

        case "$OUTPUT_DIR" in
          "$GITHUB_WORKSPACE"*) ;;
          *) echo "::error::Output dir must be within repository: $OUTPUT_DIR"; exit 1 ;;
        esac

        if [ ! -f "$SPEC_PATH" ]; then
          echo "::error::Specification file not found: $SPEC_PATH"
          exit 1
        fi

        echo "Generating $LANG code in $OUTPUT_DIR based on $SPEC_PATH..."

        # Read spec content
        SPEC_CONTENT=$(cat "$SPEC_PATH")

        # Use custom template if provided, otherwise use built-in
        if [ -n "$GEN_PROMPT_TEMPLATE" ] && [ -f "$GEN_PROMPT_TEMPLATE" ]; then
          TEMPLATE_FILE="$GEN_PROMPT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/gen_prompt.txt"
        fi

        # Read template and replace placeholders (safe: use awk for untrusted input)
        # Escape special characters for safe replacement
        SPEC_ESCAPED=$(printf '%s\n' "$SPEC_CONTENT" | sed 's/[&/\]/\\&/g')
        OUTPUT_ESCAPED=$(printf '%s\n' "$OUTPUT_DIR" | sed 's/[&/\]/\\&/g')
        LANG_ESCAPED=$(printf '%s\n' "$LANG" | sed 's/[&/\]/\\&/g')

        GEN_PROMPT=$(awk -v lang="$LANG_ESCAPED" \
                          -v spec="$SPEC_ESCAPED" \
                          -v output="$OUTPUT_ESCAPED" \
                          '{gsub(/\{LANG\}/, lang);
                            gsub(/\{SPEC_CONTENT\}/, spec);
                            gsub(/\{OUTPUT_DIR\}/, output);
                            print}' \
                          "$TEMPLATE_FILE")

        echo "$GEN_PROMPT" > /tmp/gen_prompt.txt

        # Run Claude Code CLI
        # Note: Using --dangerously-skip-permissions as it is running in a controlled self-hosted environment
        claude --dangerously-skip-permissions --model "$MODEL" < /tmp/gen_prompt.txt
