name: 'Spec to Code'
description: 'Generate code from Markdown specifications using Claude Code CLI'
inputs:
  spec-path:
    description: 'Path to the Markdown specification file'
    required: true
  output-dir:
    description: 'Directory where the code should be generated'
    required: false
    default: '.'
  language:
    description: 'Primary programming language (e.g., Python, TypeScript)'
    required: false
    default: 'TypeScript'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  gen-prompt-template:
    description: 'Path to custom generation prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API operations'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Ensure output directory exists
      shell: bash
      run: |
        # Validate and create output directory with path traversal protection
        OUTPUT_DIR="${{ inputs.output-dir }}"

        # Resolve absolute path to prevent directory traversal
        OUTPUT_DIR=$(cd "$GITHUB_WORKSPACE" && mkdir -p "$OUTPUT_DIR" && cd "$OUTPUT_DIR" && pwd)

        # Verify we're still within the workspace
        if [[ "$OUTPUT_DIR" != "$GITHUB_WORKSPACE"* ]]; then
          echo "::error::Output directory outside workspace: $OUTPUT_DIR"
          exit 1
        fi

        echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV

    - name: Validate Spec Path
      shell: bash
      run: |
        SPEC_PATH="${{ inputs.spec-path }}"

        # Resolve absolute path
        SPEC_PATH=$(cd "$GITHUB_WORKSPACE" && cd "$(dirname "$SPEC_PATH")" && pwd)/$(basename "$SPEC_PATH")

        # Verify path is within workspace
        if [[ "$SPEC_PATH" != "$GITHUB_WORKSPACE"* ]]; then
          echo "::error::Spec file outside workspace: $SPEC_PATH"
          exit 1
        fi

        # Verify file exists and is readable
        if [ ! -f "$SPEC_PATH" ]; then
          echo "::error::Specification file not found: $SPEC_PATH"
          exit 1
        fi

        if [ ! -r "$SPEC_PATH" ]; then
          echo "::error::Specification file not readable: $SPEC_PATH"
          exit 1
        fi

        echo "SPEC_PATH=$SPEC_PATH" >> $GITHUB_ENV

    - name: Generate Code with Claude Code CLI
      shell: bash
      run: |
        LANG="${{ inputs.language }}"
        MODEL="${{ inputs.claude-model }}"
        GEN_PROMPT_TEMPLATE="${{ inputs.gen-prompt-template }}"
        OUTPUT_DIR="${{ env.OUTPUT_DIR }}"
        SPEC_PATH="${{ env.SPEC_PATH }}"

        echo "Generating $LANG code in $OUTPUT_DIR based on $SPEC_PATH..."

        # Read spec content safely (escaped for use in templating)
        # Use base64 encoding to safely pass content through sed
        SPEC_CONTENT=$(cat "$SPEC_PATH" | base64 -w 0)

        # Use custom template if provided, otherwise use built-in
        if [ -n "$GEN_PROMPT_TEMPLATE" ]; then
          # Validate path to prevent directory traversal
          if [[ "$GEN_PROMPT_TEMPLATE" == *".."*"."* ]] || [[ "$GEN_PROMPT_TEMPLATE" == *"/"*".."* ]]; then
            echo "::error::Path traversal detected in template path"
            exit 1
          fi
          # Resolve to absolute path and ensure it's within allowed directories
          RESOLVED_PATH=$(cd "$GITHUB_WORKSPACE" 2>/dev/null && cd "$(dirname "$GEN_PROMPT_TEMPLATE")" 2>/dev/null && pwd)/$(basename "$GEN_PROMPT_TEMPLATE") 2>/dev/null || echo ""
          if [ -z "$RESOLVED_PATH" ] || [[ ! "$RESOLVED_PATH" == "$GITHUB_WORKSPACE"* ]] && [[ ! "$RESOLVED_PATH" == "${{ github.action_path }}"* ]]; then
            echo "::error::Template path must be within workspace or action directory"
            exit 1
          fi
          if [ -f "$RESOLVED_PATH" ]; then
            TEMPLATE_FILE="$RESOLVED_PATH"
          else
            echo "::error::Template file not found: $GEN_PROMPT_TEMPLATE"
            exit 1
          fi
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/gen_prompt.txt"
        fi

        # Read template safely
        if ! cat "$TEMPLATE_FILE" > /tmp/gen_prompt.txt; then
          echo "::error::Failed to read template file: $TEMPLATE_FILE"
          exit 1
        fi

        # Decode and insert spec content using environment variables (safer than sed)
        export SPEC_CONTENT
        export LANG
        export OUTPUT_DIR

        # Replace placeholders using envsubst instead of sed
        # This is safer as it properly escapes special characters
        GEN_PROMPT=$(envsubst '$LANG $OUTPUT_DIR' < /tmp/gen_prompt.txt)

        # Build final prompt file
        {
          echo "$GEN_PROMPT"
          echo ""
          echo "## Specification Content:"
          echo '```'
          echo "$SPEC_CONTENT" | base64 -d
          echo '```'
        } > /tmp/gen_prompt_final.txt

        # Check Claude CLI availability before invoking
        if ! command -v claude &> /dev/null; then
          echo "::error::Claude CLI not found. Please install Claude CLI first."
          echo "  Visit https://claude.ai/ for installation instructions."
          exit 1
        fi

        # Run Claude Code CLI in safe mode (no --dangerously-skip-permissions)
        claude --model "$MODEL" < /tmp/gen_prompt_final.txt
