name: 'Auto Document'
description: 'Automatically update documentation based on code changes using Claude Code CLI'
inputs:
  source-path:
    description: 'Path to source code to analyze'
    required: false
    default: '.'
  doc-path:
    description: 'Path to the document to update (e.g., README.md)'
    required: false
    default: 'README.md'
  claude-model:
    description: 'Claude model to use (default: sonnet)'
    required: false
    default: 'sonnet'
  doc-prompt-template:
    description: 'Path to custom doc prompt template (optional, uses built-in template if not specified)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update Documentation with Claude Code CLI
      shell: bash
      run: |
        SOURCE_PATH="${{ inputs.source-path }}"
        DOC_PATH="${{ inputs.doc-path }}"
        MODEL="${{ inputs.claude-model }}"

        echo "Updating $DOC_PATH based on source in $SOURCE_PATH..."

        DOC_PROMPT_TEMPLATE="${{ inputs.doc-prompt-template }}"

        # Use custom template if provided, otherwise use built-in
        if [ -n "$DOC_PROMPT_TEMPLATE" ] && [ -f "$DOC_PROMPT_TEMPLATE" ]; then
          TEMPLATE_FILE="$DOC_PROMPT_TEMPLATE"
        else
          TEMPLATE_FILE="${{ github.action_path }}/templates/doc_prompt.txt"
        fi

        # Read template and replace placeholders
        DOC_PROMPT=$(sed -e "s#{SOURCE_PATH}#$SOURCE_PATH#g" \
                          -e "s#{DOC_PATH}#$DOC_PATH#g" \
                          "$TEMPLATE_FILE")

        echo "$DOC_PROMPT" > /tmp/doc_prompt.txt

        # Run Claude Code CLI
        claude --dangerously-skip-permissions --model "$MODEL" < /tmp/doc_prompt.txt
