#!/usr/bin/env python3
"""
Core Function Verification Script
Generated by Repo Genesis Auditor

This script verifies the core functions claimed by the repository:
- Action structure validation
- Test coverage
- Documentation completeness
- Integration test coverage
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Any, List


@dataclass
class VerificationResult:
    """Verification result data class"""
    function_id: str
    scenario_name: str
    passed: bool
    actual_output: Any
    expected_output: Any
    error_message: str | None = None
    interpretation: str = ""


def run_command(cmd: List[str], cwd: Path | None = None) -> tuple[bool, str, str]:
    """Run a command and return success, stdout, stderr"""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=cwd,
            timeout=60
        )
        return result.returncode == 0, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return False, "", "Command timed out"
    except Exception as e:
        return False, "", str(e)


def verify_action_structure() -> VerificationResult:
    """CF-STRUCT-001: 全Actionsの構造的完全性"""
    print("\n🔍 Verifying: Action Structure (CF-STRUCT-001)")

    # Run pytest to check action structure
    success, stdout, stderr = run_command([
        "pytest", "tests/", "-v", "-k", "test_action",
        "--tb=no", "-q"
    ])

    # Parse output - look for summary line with '=' and 'passed'
    lines = stdout.split('\n')
    summary_lines = [l for l in lines if 'passed' in l and '=' in l]

    if not summary_lines:
        return VerificationResult(
            function_id="CF-STRUCT-001",
            scenario_name="全Actionsの構造的完全性",
            passed=False,
            actual_output=stdout[:500],
            expected_output=">= 135 passed",
            error_message="Could not parse test output",
            interpretation="テスト実行に失敗したか、出力形式が変更されている"
        )

    # Extract pass count using regex
    summary_line = summary_lines[-1]
    match = re.search(r'(\d+)\s+passed', summary_line)
    
    if not match:
        return VerificationResult(
            function_id="CF-STRUCT-001",
            scenario_name="全Actionsの構造的完全性",
            passed=False,
            actual_output=summary_line,
            expected_output=">= 135 passed",
            error_message="Could not extract pass count",
            interpretation="テスト結果のパースに失敗"
        )
    
    passed_count = int(match.group(1))

    # Expected count should be at least 140 (139 current + margin for new tests)
    passed = passed_count >= 135

    return VerificationResult(
        function_id="CF-STRUCT-001",
        scenario_name="全Actionsの構造的完全性",
        passed=passed,
        actual_output=f"{passed_count} passed",
        expected_output=">= 135 passed",
        interpretation=(
            f"全13個のActionが構造的に正しく実装されている（{passed_count} tests passed）"
            if passed
            else f"一部のActionで構造エラーがある（{passed_count}/140 passed）"
        )
    )


def verify_test_coverage() -> VerificationResult:
    """QA-001: テストカバレッジ >= 70%"""
    print("\n🔍 Verifying: Test Coverage (QA-001)")

    success, stdout, stderr = run_command([
        "pytest", "--cov=actions", "--cov=scripts",
        "--cov-report=term", "--tb=no", "-q"
    ])

    # Parse coverage percentage
    lines = stdout.split('\n')
    coverage_line = [l for l in lines if 'coverage:' in l.lower() or '%' in l]

    if not coverage_line:
        return VerificationResult(
            function_id="QA-001",
            scenario_name="テストカバレッジ >= 70%",
            passed=False,
            actual_output=stdout,
            expected_output="Coverage: >= 70%",
            error_message="Could not find coverage in output",
            interpretation="カバレッジ測定に失敗"
        )

    # Extract coverage percentage
    # Format: "TOTAL                             927      65  92.99%"
    for line in coverage_line:
        if 'TOTAL' in line:
            parts = line.split()
            if len(parts) >= 4:
                try:
                    coverage_pct = float(parts[-1].rstrip('%'))
                    passed = coverage_pct >= 70.0

                    return VerificationResult(
                        function_id="QA-001",
                        scenario_name="テストカバレッジ >= 70%",
                        passed=passed,
                        actual_output=f"{coverage_pct}%",
                        expected_output=">= 70%",
                        interpretation=(
                            f"テストカバレッジ{coverage_pct}%は目標の70%を{'大幅に' if coverage_pct >= 90 else ''}上回っている"
                            if passed
                            else f"テストカバレッジ{coverage_pct}%が目標の70%を下回っている"
                        )
                    )
                except (ValueError, IndexError):
                    pass

    return VerificationResult(
        function_id="QA-001",
        scenario_name="テストカバレッジ >= 70%",
        passed=False,
        actual_output=stdout,
        expected_output=">= 70%",
        error_message="Could not parse coverage percentage",
        interpretation="カバレッジ率のパースに失敗"
    )


def verify_integration_test_coverage() -> VerificationResult:
    """QA-003: Integration Test Coverage 100%"""
    print("\n🔍 Verifying: Integration Test Coverage (QA-003)")

    repo_root = Path.cwd()
    integration_test_dir = repo_root / "tests" / "integration"

    if not integration_test_dir.exists():
        return VerificationResult(
            function_id="QA-003",
            scenario_name="Integration Test Coverage 100%",
            passed=False,
            actual_output="tests/integration/ directory not found",
            expected_output="13 integration test files",
            error_message="Integration test directory missing",
            interpretation="Integration testディレクトリが存在しない"
        )

    # Count integration test files
    test_files = list(integration_test_dir.glob("test_*_integration.py"))
    test_count = len(test_files)

    passed = test_count >= 13

    return VerificationResult(
        function_id="QA-003",
        scenario_name="Integration Test Coverage 100%",
        passed=passed,
        actual_output=f"{test_count} integration test files",
        expected_output="13 integration test files",
        interpretation=(
            f"全13個のActionに対してIntegration Testが作成されている（{test_count}/13）"
            if passed
            else f"Integration Testが不足している（{test_count}/13）"
        )
    )


def verify_documentation_coverage() -> VerificationResult:
    """DOC-001: 全Actionsにドキュメントが存在"""
    print("\n🔍 Verifying: Documentation Coverage (DOC-001)")

    repo_root = Path.cwd()

    # Count example files
    examples_dir = repo_root / "examples"
    example_files = list(examples_dir.glob("*-example.yml")) if examples_dir.exists() else []
    example_count = len(example_files)

    # Count instruction files
    instructions_dir = repo_root / "instructions"
    instruction_files = list(instructions_dir.glob("*.md")) if instructions_dir.exists() else []
    instruction_count = len(instruction_files)

    passed = example_count >= 13 and instruction_count >= 13

    return VerificationResult(
        function_id="DOC-001",
        scenario_name="全Actionsにドキュメントが存在",
        passed=passed,
        actual_output=f"Examples: {example_count}, Instructions: {instruction_count}",
        expected_output="Examples: >= 13, Instructions: >= 13",
        interpretation=(
            f"全Actionにexampleファイルとinstructionドキュメントが存在する"
            if passed
            else f"ドキュメントが不足している（Examples: {example_count}/13, Instructions: {instruction_count}/13）"
        )
    )


def verify_ai_review_metrics() -> VerificationResult:
    """QA-002: AIレビュー受入率 >= 70%"""
    print("\n🔍 Verifying: AI Review Acceptance Rate (QA-002)")

    repo_root = Path.cwd()
    metrics_file = repo_root / "metrics" / "review_metrics.json"

    if not metrics_file.exists():
        return VerificationResult(
            function_id="QA-002",
            scenario_name="AIレビュー受入率 >= 70%",
            passed=False,
            actual_output="metrics/review_metrics.json not found",
            expected_output="Acceptance rate >= 70%",
            error_message="No review metrics data available",
            interpretation=(
                "CRITICAL: AIレビュー品質の核心的指標が測定できない。\n"
                "metrics/review_metrics.json が存在しないため、受入率を計測できない。\n"
                "即時のアクションが必要：パイロットプロジェクトでのレビューデータ収集開始"
            )
        )

    # Try to calculate acceptance rate
    success, stdout, stderr = run_command([
        "python", "scripts/calculate_acceptance_rate.py",
        "--time-period", "30d"
    ])

    if not success:
        return VerificationResult(
            function_id="QA-002",
            scenario_name="AIレビュー受入率 >= 70%",
            passed=False,
            actual_output=stdout or stderr,
            expected_output="Acceptance rate >= 70%",
            error_message="Failed to calculate acceptance rate",
            interpretation="受入率計算に失敗。データ形式に問題がある可能性"
        )

    # Parse output (simplified)
    if "N/A" in stdout or "insufficient data" in stdout.lower():
        return VerificationResult(
            function_id="QA-002",
            scenario_name="AIレビュー受入率 >= 70%",
            passed=False,
            actual_output="Insufficient data",
            expected_output="Acceptance rate >= 70%",
            error_message="Not enough review data",
            interpretation="レビューデータが不足している。20件以上のデータが必要"
        )

    # Extract acceptance rate (implementation would parse the actual output)
    # For now, assume failure
    return VerificationResult(
        function_id="QA-002",
        scenario_name="AIレビュー受入率 >= 70%",
        passed=False,
        actual_output=stdout[:200],
        expected_output="Acceptance rate >= 70%",
        error_message="Could not determine acceptance rate",
        interpretation="受入率のパースに失敗、または目標未達"
    )


def main():
    """Main verification entry point"""

    print("=" * 70)
    print("CORE FUNCTION VERIFICATION REPORT")
    print("=" * 70)
    print("Repo Genesis Auditor v2.0")
    print("Repository: github-actions-actions")
    print("Run ID: 2026-02-08T04:40:00Z")
    print("=" * 70)

    # Run all verifications
    results = [
        verify_action_structure(),
        verify_test_coverage(),
        verify_integration_test_coverage(),
        verify_documentation_coverage(),
        verify_ai_review_metrics(),
    ]

    # Print results
    print("\n" + "=" * 70)
    print("VERIFICATION RESULTS")
    print("=" * 70)

    passed_count = sum(1 for r in results if r.passed)
    total_count = len(results)

    for r in results:
        status = "✅ PASS" if r.passed else "❌ FAIL"
        print(f"\n{status} [{r.function_id}] {r.scenario_name}")
        print(f"  結果: {r.actual_output}")
        print(f"  期待: {r.expected_output}")
        print(f"  解釈: {r.interpretation}")
        if r.error_message:
            print(f"  エラー: {r.error_message}")

    # Summary
    print("\n" + "=" * 70)
    print(f"SUMMARY: {passed_count}/{total_count} passed ({passed_count/total_count*100:.1f}%)")
    print("=" * 70)

    if passed_count == total_count:
        print("✅ 判定: PASS - 全ての検証に合格")
        print("\nリポジトリの存在意義が検証された")
        return 0
    elif passed_count >= total_count * 0.7:
        print("⚠️  判定: CONDITIONAL PASS - 一部の検証が不合格")
        print("\n改善が必要な領域:")
        for r in results:
            if not r.passed:
                print(f"  - {r.function_id}: {r.interpretation.split('.')[0]}")
        print("\n推奨アクション:")
        print("  1. 失敗した検証項目の改善提案を確認（.audit/proposal/changes/）")
        print("  2. 優先度の高い問題から対開")
        return 0
    else:
        print("❌ 判定: FAIL - 多くの検証が不合格")
        print("\n深刻な問題が存在する")
        return 1


if __name__ == "__main__":
    sys.exit(main())
