#!/usr/bin/env python3
"""
Core Function Verification Script
Generated by Repo Genesis Auditor

Verifies that the repository's core functions work as intended.
"""
import json
import subprocess
import sys
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Any, Optional


@dataclass
class VerificationResult:
    function_id: str
    scenario_name: str
    passed: bool
    actual_output: Any
    expected_output: Any
    error_message: Optional[str] = None
    interpretation: str = ""


def verify_cf001_ai_review() -> VerificationResult:
    """CF-001: AIによるコードレビューと自動マージができる"""

    # 1. テストで検証（review-and-merge Action）
    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "tests/test_review_and_merge/", "-v", "--tb=short"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=Path("/home/jinno/github-actions-actions")
        )

        actual = {
            "exit_code": result.returncode,
            "tests_run": result.stdout.count(" PASSED")
        }

    except subprocess.TimeoutExpired:
        return VerificationResult(
            function_id="CF-001",
            scenario_name="AIレビュー機能のテスト検証",
            passed=False,
            actual_output=None,
            expected_output="Exit code 0",
            error_message="Test execution timed out",
            interpretation="テスト実行が時間内に完了しなかった。パフォーマンスの問題がある可能性。"
        )
    except Exception as e:
        return VerificationResult(
            function_id="CF-001",
            scenario_name="AIレビュー機能のテスト検証",
            passed=False,
            actual_output=None,
            expected_output="Exit code 0",
            error_message=str(e),
            interpretation="テスト実行自体が失敗。環境設定を確認せよ。"
        )

    # 2. 期待値との比較
    expected = {
        "exit_code": 0,
        "minimum_tests": 1
    }

    passed = actual["exit_code"] == 0 and actual["tests_run"] >= expected["minimum_tests"]

    return VerificationResult(
        function_id="CF-001",
        scenario_name="AIレビュー機能のテスト検証",
        passed=passed,
        actual_output=actual,
        expected_output=expected,
        interpretation=(
            "AIレビュー機能のテストが正常にパスした。"
            if passed
            else f"テストが失敗または実行されなかった。Exit code: {actual['exit_code']}"
        )
    )


def verify_cf002_spec_to_code() -> VerificationResult:
    """CF-002: Markdown仕様書からコードを自動生成できる"""

    # 1. テストで検証（spec-to-code Action）
    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "tests/test_spec_to_code/", "-v", "--tb=short"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=Path("/home/jinno/github-actions-actions")
        )

        actual = {
            "exit_code": result.returncode,
            "tests_run": result.stdout.count(" PASSED")
        }

    except subprocess.TimeoutExpired:
        return VerificationResult(
            function_id="CF-002",
            scenario_name="Spec-to-Code機能のテスト検証",
            passed=False,
            actual_output=None,
            expected_output="Exit code 0",
            error_message="Test execution timed out",
            interpretation="テスト実行が時間内に完了しなかった。"
        )
    except Exception as e:
        return VerificationResult(
            function_id="CF-002",
            scenario_name="Spec-to-Code機能のテスト検証",
            passed=False,
            actual_output=None,
            expected_output="Exit code 0",
            error_message=str(e),
            interpretation="テスト実行自体が失敗。"
        )

    # 2. 期待値との比較
    expected = {
        "exit_code": 0,
        "minimum_tests": 1
    }

    passed = actual["exit_code"] == 0 and actual["tests_run"] >= expected["minimum_tests"]

    return VerificationResult(
        function_id="CF-002",
        scenario_name="Spec-to-Code機能のテスト検証",
        passed=passed,
        actual_output=actual,
        expected_output=expected,
        interpretation=(
            "Spec-to-Code機能のテストが正常にパスした。"
            if passed
            else f"テストが失敗。Exit code: {actual['exit_code']}"
        )
    )


def verify_cf003_action_fixer() -> VerificationResult:
    """CF-003: WorkflowのエラーをAIが自動修正できる"""

    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "tests/test_action_fixer/", "-v", "--tb=short"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=Path("/home/jinno/github-actions-actions")
        )

        actual = {
            "exit_code": result.returncode,
            "tests_run": result.stdout.count(" PASSED")
        }

    except Exception as e:
        return VerificationResult(
            function_id="CF-003",
            scenario_name="Action Fixer機能のテスト検証",
            passed=False,
            actual_output=None,
            expected_output="Exit code 0",
            error_message=str(e),
            interpretation="テスト実行失敗。"
        )

    expected = {
        "exit_code": 0,
        "minimum_tests": 1
    }

    passed = actual["exit_code"] == 0 and actual["tests_run"] >= expected["minimum_tests"]

    return VerificationResult(
        function_id="CF-003",
        scenario_name="Action Fixer機能のテスト検証",
        passed=passed,
        actual_output=actual,
        expected_output=expected,
        interpretation=(
            "Action Fixer機能のテストが正常にパスした。"
            if passed
            else f"テストが失敗。Exit code: {actual['exit_code']}"
        )
    )


def verify_cf006_test_coverage() -> VerificationResult:
    """CF-006: 全てのAI ActionsがDry Run検証をパスする（テストカバレッジ）"""

    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "tests/", "--cov=.", "--cov-report=json", "-v"],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=Path("/home/jinno/github-actions-actions")
        )

        # カバレッジJSONを読み取る
        coverage_path = Path("/home/jinno/github-actions-actions/coverage.json")
        if coverage_path.exists():
            with open(coverage_path) as f:
                coverage_data = json.load(f)
            actual_coverage = coverage_data.get("totals", {}).get("percent_covered", 0)
        else:
            actual_coverage = 0

        actual = {
            "exit_code": result.returncode,
            "coverage_percent": actual_coverage
        }

    except Exception as e:
        return VerificationResult(
            function_id="CF-006",
            scenario_name="テストカバレッジの検証",
            passed=False,
            actual_output=None,
            expected_output="Coverage >= 70%",
            error_message=str(e),
            interpretation="カバレッジ計測失敗。"
        )

    expected = {
        "exit_code": 0,
        "coverage_percent": 70
    }

    passed = actual["exit_code"] == 0 and actual["coverage_percent"] >= expected["coverage_percent"]

    return VerificationResult(
        function_id="CF-006",
        scenario_name="テストカバレッジの検証",
        passed=passed,
        actual_output=actual,
        expected_output=expected,
        interpretation=(
            f"テストカバレッジ{actual['coverage_percent']:.2f}%は目標の70%を達成している。"
            if passed
            else f"テストカバレッジ{actual['coverage_percent']:.2f}%が目標の70%を下回っている。"
        )
    )


def verify_all_actions_have_documentation() -> VerificationResult:
    """全てのActionにREADMEとSetup Guideが存在するか確認"""

    actions_dir = Path("/home/jinno/github-actions-actions/actions")
    instructions_dir = Path("/home/jinno/github-actions-actions/instructions")

    actions = [d for d in actions_dir.iterdir() if d.is_dir() and not d.name.startswith("_")]

    missing_readme = []
    missing_instructions = []

    for action_dir in actions:
        readme_path = action_dir / "README.md"
        instruction_path = instructions_dir / f"{action_dir.name}.md"

        if not readme_path.exists():
            missing_readme.append(action_dir.name)

        if not instruction_path.exists():
            missing_instructions.append(action_dir.name)

    actual = {
        "total_actions": len(actions),
        "missing_readme": missing_readme,
        "missing_instructions": missing_instructions
    }

    expected = {
        "total_actions": len(actions),
        "missing_readme": [],
        "missing_instructions": []
    }

    passed = len(missing_readme) == 0 and len(missing_instructions) == 0

    return VerificationResult(
        function_id="QA-COMMON-002",
        scenario_name="ドキュメント網羅性の確認",
        passed=passed,
        actual_output=actual,
        expected_output=expected,
        interpretation=(
            f"全てのActionにドキュメントが存在している。"
            if passed
            else f"READMEが不足: {missing_readme}, Setup Guideが不足: {missing_instructions}"
        )
    )


def main():
    """全Core Functionを検証し、レポートを生成"""

    results = [
        verify_cf001_ai_review(),
        verify_cf002_spec_to_code(),
        verify_cf003_action_fixer(),
        verify_cf006_test_coverage(),
        verify_all_actions_have_documentation(),
    ]

    # レポート生成
    print("=" * 60)
    print("CORE FUNCTION VERIFICATION REPORT")
    print("=" * 60)

    passed_count = sum(1 for r in results if r.passed)
    total_count = len(results)

    for r in results:
        status = "✅ PASS" if r.passed else "❌ FAIL"
        print(f"\n{status} [{r.function_id}] {r.scenario_name}")
        print(f"  解釈: {r.interpretation}")
        if r.error_message:
            print(f"  エラー: {r.error_message}")

    print("\n" + "=" * 60)
    print(f"SUMMARY: {passed_count}/{total_count} passed")

    if passed_count == total_count:
        print("判定: ✅ リポジトリの存在意義が検証された")
    else:
        print("判定: ⚠️  一部の機能で検証未完了または問題あり")
        print("\n次のアクション:")
        for r in results:
            if not r.passed:
                print(f"  - {r.function_id}: {r.interpretation}")

    # 結果をJSONで保存
    output_path = Path("/home/jinno/github-actions-actions/.audit/output/verification_result.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Convert dataclass to dict for JSON serialization
    results_dict = [asdict(r) for r in results]

    output_path.write_text(json.dumps(results_dict, ensure_ascii=False, indent=2))

    print(f"\nレポートを保存しました: {output_path}")

    sys.exit(0 if passed_count == total_count else 1)


if __name__ == "__main__":
    main()
